base-path = "pages"
# default: empty string
#base-url = "/my-project"

# if not specified, the first available entry in
# ["versions", "vanguard", "variants"] is used
#default = "latest"

# these will be injected first, in the given order
vanguard = [
    "latest",
]

# versions (i.e. Git tags) will be injected in the given order
versions = [
    "0.1.1",
    "0.1.0",
]

# variants (i.e. Git branches) will be injected in alphabetical order
variants = [
]

# these will not be part of any version lists
unlisted = [
    "experimental-af",
]

vanguard-warning = "vanguard-warning.html"
# NB: the first entry in "versions" will never get a warning
versions-warning = "versions-warning.html"
# if no template is specified, no warnings will be injected
#variants-warning = "variants-warning.html"
#unlisted-warning = "unlisted-warning.html"

# only needed if (some of) the default templates shall be overridden
#templates-path = "templates"
# TODO: rename to template-path?
#template-path = "templates"
